server:
  port: 8080

spring:
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

sso:
  authorize_url: http://127.0.0.1:8090/oauth/authorize
  token_url: http://127.0.0.1:8090/oauth/token
  redirect_uri: http://127.0.0.1:8081/user/callback
  client_id: client_1
  client_secret: 123456
  scope: all
  grant_type: authorization_code