server:
  port: 8090

spring:
  redis:
    database: 5
    port: 6379
    host: 10.1.1.147
    password: 123456
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://122.51.148.46:3306/db_sso?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security: DEBUG
